input {
  beats {
    host => "127.0.0.1"
    port => 5044
  }
}

filter {
  date {
    match => ["ts", "UNIX"]
    target => "@timestamp"
  }
  mutate {
    add_field => { "logstash_pipeline" => "zeek_pipeline" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch.local:9200"]
    index => "active-zeek"
    data_stream => false
    ilm_enabled => false
    manage_template => false
  }
}
